server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/test002?serverTimezone=GMT%2B8
mybatis:
  type-aliases=package: com.offcn.pojo
  mapper-locations: classpath:com/offcn/mapper/*.xml
